function parsave_non_avg(fname, B_gd,C_gd,W_gd, ...
       corr_train,corr_test,Y_train,Y_test, ...
       B_init,C_init,W_init, ...
       lambda,lambda_1,lambda_2,lambda_3,lr1)
save(fname,  'B_gd','C_gd','W_gd', ...
       'corr_train','corr_test','Y_train','Y_test', ...
       'B_init','C_init','W_init', ...
       'lambda','lambda_1','lambda_2','lambda_3','lr1')
end